# Github Actions
# /Users/matthewsimon/Documents/Github/solomon-Desktop-App/.github/workflows/release.yml

name: Build and Publish Electron App

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install

      - name: Build Renderer
        working-directory: packages/renderer
        run: pnpm run build

      - name: Build Electron App
        working-directory: packages/electron
        run: pnpm run build

      - name: Publish Release
        if: startsWith(github.ref, 'refs/tags/v')
        working-directory: packages/electron
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm run dist