name: Build and Publish Electron App

permissions:
  contents: write
  actions: read

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      # 1. Check out your repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Node.js (v18). No caching so no pnpm conflict.
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install pnpm using pnpm/action-setup
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      # 4. Verify pnpm (optional check)
      - name: Check pnpm version
        run: pnpm --version

      # 5. Install dependencies
      - name: Install Dependencies
        run: pnpm install

      # 6. Build the Next.js renderer
      - name: Build Renderer
        working-directory: packages/renderer
        run: pnpm run build

      # 7. Build the Electron app
      - name: Build Electron App
        working-directory: packages/electron
        run: pnpm run build

      # 8. Publish Release if on a new tag matching "v*.*.*"
      - name: Publish Release
        if: startsWith(github.ref, 'refs/tags/v')
        working-directory: packages/electron
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            npx electron-builder --publish always --mac
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            npx electron-builder --publish always --win
          else
            npx electron-builder --publish always --linux
          fi