name: Build and Publish Electron App

permissions:
  contents: write  # Needed to create/edit releases, all else defaults to 'none'

on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your repository code
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Node.js (v16)
      # Remove "cache: 'pnpm'" so it won't try to run pnpm before it's installed
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install pnpm using the official pnpm/action-setup@v2
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          # Change '8' to your preferred pnpm version
          version: 8

      # 4. Verify pnpm installed (optional)
      - name: Check pnpm version
        run: pnpm --version

      # 5. Install dependencies (monorepo root)
      - name: Install Dependencies
        run: pnpm install

      # 6. Build the Next.js renderer
      - name: Build Renderer
        working-directory: packages/renderer
        run: pnpm run build

      # 7. Build the Electron app
      - name: Build Electron App
        working-directory: packages/electron
        run: pnpm run build

      # 8. Publish Release if on a new tag matching "v*.*.*"
      - name: Publish Release
        if: startsWith(github.ref, 'refs/tags/v')
        working-directory: packages/electron
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: pnpm run dist