name: Test PAT

permissions:
  contents: write  # Needed to create/edit releases, all else defaults to 'none'

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Test GitHub API Access
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          curl -H "Authorization: token $GH_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/releases